### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gitomato**

### CODE REVIEW

**Comment by Hywan** [comment]
Thananks!

**Comment by Hywan** [comment]
And welcome on board, https://hoa-project.net/En/Community.html :-).

**Comment by gitomato** [comment]
For fixing a simple typo, what an honor! Thanks!

**Comment by Hywan** [comment]
Everyone has the same treatment :-). Hope it motivates you to contribute to something else (even if it's not this project) ;-)!

**Pull request merged**
